### ISSUE TITLE
[TEST] 아이엠 포트 테스트코드 error

### ISSUE THREAD

**Issue by stopmin** [kakao-tech-campus-2nd-step3/Team10_BE#118]
### 🐞 Describe

> 로컬/배포 환경에서 Iamport 에러가 발생합니다.

1. IamportTest 에러

- 에러 설명: IamportTest > portonePrePaymentRegister_Test() 메서드에서 IamportResponseException이 발생하며, 이는 retrofit2.HttpException에 의해 발생합니다.
- 원인: 이 에러는 주로 Iamport API의 인증 문제(API 키 또는 비밀 키 누락, 잘못된 설정)나 네트워크 연결 문제로 인해 발생할 수 있습니다. 로컬에서는 정상적으로 동작하더라도, GitHub Actions 환경에서는 API 키가 정확히 설정되지 않아 발생할 가능성이 있습니다.
- 근데 로컬에서 확인해보니 키가 없네요

### 📄 Logs

```shell
<img width="1099" alt="스크린샷 2024-11-09 오전 1 37 05" src="https://github.com/user-attachments/assets/1847e776-bfe6-437b-873e-c92f5be8688b">
```

### 🌏 Environment

-

### 🙋🏻 More

-

**Comment by amm0124** [comment]
키값을 안넣은..

**Comment by amm0124** [comment]
해결이됐다!!
