### ISSUE TITLE
jwtUtil 수정

### ISSUE THREAD

**Issue by jjt4515** [kakao-tech-campus-2nd-step3/Team10_BE#24]
### ✏️ Describe

건호님의 피드백을 반영할 것입니다

### ✅ TO-DO

- [ ] jwt subject로 id, 클레임으로 email, role 넣는 방식으로 수정하기

**Comment by amm0124** [comment]
천천히 다시 읽어보니 수정 사항이 생겨서 댓글을 다시 달아요

## 회원가입 시 , 굳이 토큰을 만들어서 보내줄 필요가 없다.

이유는 토큰 발급은 그냥 security단에서 처리하는 것이 좋아 보여요. 왜냐하면 회원 가입은 단 한 번 하니까요. 그냥 ID/password가 존재하지 않는다면 db에 저장하고 200 . ok status만 보내도 괜찮을 것 같아요. 
요청은 프론트가 다시 한 번 해도 되는 거니까요. (프론트한테 물어보니 괜찮다고 하시네요)

## spring mvc가 해야할 일은 refresh token 재발급 및 회원 가입만 해도 된다.

로그아웃 등의 기능은 필터를 구현하여 security context에서 처리할 수 있기 때문에 mvc에서 할 필요가 없습니다~
이 기능은 지워주세요

## 인터페이스를 사용해서 상호 호환성을 달성해야 한다.
GPT가 만들어준 예시를 보고 제 생각을 적겠습니다
redis사용하는 부분인데, 아래와 같이 interface를 만들어서 구현하는 것이 좋아보입니다. 그리고 service가 너무 repository의 역할을 담당하고 있다고 해야 하나요
redis service와 redis repository를 분리한 다음, interface를 사용해서 상호 호환성을 달성하는 것이 좋아 보여요 
왜냐하면 우리는 db를 갈아 끼워야 하니까요. (확장성 측면)

아래와 같이 구현한 다음

![image](https://github.com/user-attachments/assets/0f42341c-28ab-49b7-92ac-1837cbe27121)

![image](https://github.com/user-attachments/assets/9ecf9183-5ce2-4e2a-99a3-750d2855fc24)

![image](https://github.com/user-attachments/assets/f5d35255-20e9-4b7c-aab5-5ba3b48827bc)

black list를 관리하는 서비스에서 repository만 갈아 끼우면 되도록 구현해보는 것이 좋아 보여요. (refresh token도 이하 동일)

또, RefreshToken이라는 entity가 존재하더라고요. 저는 이거를 보고 entity package안에 들어가 있어서 entity로만 사용되는 줄 알았어요. 근데 service로직까지 포함을 하고 있었습니다. 이를 분리해서 구현해보는 것도 좋아보여요

항상 저희가 JPA만 쓸 것이 아니고, redis만 쓸 것이 아니고, h2 hibernate만 사용할 것이 아니니까요.

이를 공부해보시면 객체지향 및 인터페이스에 대해 좀 더 잘 알게 될 것이라고 생각합니다. 코드의 확장성 측면으로도 좋고요.

![image](https://github.com/user-attachments/assets/5df60cc3-3dad-4a73-a4d3-1ed631b4c5cd)


## DTO - LoginRequest
이 dto가 사용되는 곳은 회원가입 service더라고요. 이름을 Login request가 아닌
Signup requset 형태로 바꾸는 것이 좋아보여요

## 계층 구조 - 순수 저의 생각

auth라는 package는 사용자의 인증 및 인가 및 로그인 등등을 처리하는 package입니다. 이건 순수 제 생각일 수 있는데, 약간 정리가 안 되어 보이는 거 같아요
service에서 db 처리 하는 것 ,,, 등등

그래서 계층 구조를 이렇게 설정해보는 것은 어떤가요?
저희가 domain을 패키지로 나누어서 해보자고 이야기를 했으니 이렇게 하는 것이 보기 훨씬 좋아 보입니다.

![image](https://github.com/user-attachments/assets/564e2d41-a14e-4af4-b1c9-7bcf600ccff1)

그리고 jwt util경우는 global에서 쓰이는 것 보다는 auth에서만 사용되니까 auth package 하위로 이동하는 것이 좋아보여요~

댓글 다시 함 달았습니다! @jjt4515  나중에 함 봐주세요 (PR에잇는내용)
