### ISSUE TITLE
Order 도메인을 생성한다

### ISSUE THREAD

**Issue by stopmin** [kakao-tech-campus-2nd-step3/Team10_BE#28]
### Order 도메인을 생성합니다.
- Order는 상품에 관한 Order입니다.
- Order에는 상태가 필요합니다.
  - 주문 완료/배송 처리/배송 중/배송 완료와 같은 **상태**가 필요합니다.
 
### OrderProduct를 생성합니다.
- Order와 OrderProduct를  1:N으로 연관관계를 맺어야 합니다.
- Product와 ManyToOne으로 정의하셔되고 안하셔도 될 것 같습니다. ProductId만 명시해주시면 됩니다.

### ✅ TO-DO

- [ ] Order를 생성할 때 해당 Product가 품절인지 아닌지 검증한다. 만약 상품 중 하나라도 품절이면 실패한다.
- [ ] Member 연결한다.
- [ ] 배송지는 Order에 별도로 추가해준다. (추후에 Member의 위치가 수정될 때를 대응)

### 🙋🏻 More

최소한만 써둔거라 작업하시면서 추가적으로 작업되는 부분이 있을 것 같습니다.

**Comment by amm0124** [comment]
좋습니다 ~~
