### ISSUE TITLE
소셜 로그인 및 server login 연동

### ISSUE THREAD

**Issue by amm0124** [kakao-tech-campus-2nd-step3/Team10_BE#46]
### ✏️ Describe

소셜 로그인 및 server login 연동 기능을 추가합니다.
카카오 개발자 공식 문서에서 보면 단순히 이메일, 전화번호 이런 것으로 연동하는 것은 권장하지 않는다고 적혀 있었어요. 
권장하는 로직은 SMS, email 인증(본인임을 확실하게 확인) 및 providerId 등을 사용하라고 적혀있던데 이 기능은 일단 제외하고 그냥 email이 같다면 바로 연동시키는 방향으로 구현하겠습니다 ~

### ✅ TO-DO

- signup controller에서 기존 계정을 조회합니다. 만약 존재한다면 계정 연동을 추가하겠습니다. 근데 review나 order는 아직 완성이 되지 않아서 수도코드 및 주석처리해서 올려놓겠습니다.
- 회원 가입 시, 기존 계정이 존재한다면 연동하는 방향으로 구현하겠습니다. 

### 🙋🏻 More

연동 시나리오가 2가지 존재합니다. 

1. 소셜로그인으로 회원 가입 했을 때, 이미 서버에서 회원 가입을 진행 한 경우. (즉 서버 회원 가입이 선행된 경우)
- 이 케이스는 security - DefaultOAuth2UserService를 상속한 필터에서 진행합니다 . 

2. 서버에서 회원 가입을 했을 때, 이미 소셜 로그인으로 회원 가입 진행 한 경우 (즉 소셜 로그인으로 가입이 선행된 경우)
- 이 경우는 api/sign-up 요청에서 처리하도록 하겠습니다

**Comment by stopmin** [comment]
로그인에 진심인 남자

**Comment by amm0124** [comment]
> 로그인에 진심인 남자

눈물 흘리는 중
