### ISSUE TITLE
시큐리티 문제로 코드가 돌아가지 않는 문제 해결

### ISSUE THREAD

**Issue by amm0124** [kakao-tech-campus-2nd-step3/Team10_BE#47]
### 🐞 Describe

master branch에 잘못된 merge로 컴파일 되지 않는 코드가 올라와서 임시로 수정해서 다시 올립니다.

### 📄 Logs

```shell
x
```

### 🌏 Environment

패키지 이름 변경 및 임시로 주석 처리 

### 🙋🏻 More

merge를 잘 하자.. 
오늘내일중으로 인증인가는 다 될 거 같아요. .. 빨리 끝내고 메인 기능 개발하고 싶습니다

**Comment by stopmin** [comment]
작업 완료하셔서 이슈 닫겠습니다~
