### ISSUE TITLE
PR 템플릿 수정 및 Issue 템플릿 세부화  

### ISSUE THREAD

**Issue by amm0124** [kakao-tech-campus-2nd-step3/Team10_BE#6]
### ✏️ Describe

Issue 템플릿이 현재 2가지 있는데 조금 더 세부적으로 작성하려고 합니다

### ✅ TO-DO

- pr 템플릿 TODO 삭제 및 간단화
- Issue 세부화 

### 🙋🏻 More

없어용

**Comment by stopmin** [comment]
갓건호~~!!
