### ISSUE TITLE
entity 등록할 때 이미지도 받게 하기

### ISSUE THREAD

**Issue by canyos** [kakao-tech-campus-2nd-step3/Team10_BE#75]
### ✏️ Describe

이미지추가하는 api추가하기
entity에도 list<imageUrl>넣어야하할듯

### ✅ TO-DO

- [ ] 이미지도 입력받기
- [ ] 이미지 저장하기
- [ ] 불러올때 이미지도 가져오기

**Comment by jjt4515** [comment]
이미지 추가, 가져오기 api는 제가 하나로 통합해서 작성할게요
